/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package substituicao;

import java.awt.Color;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author arthu
 */

public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
        
        int n = 4;
        
        Processo.geraMatriz(n);
        
        this.mostraMatriz(Processo.getMatriz(), n);
        
       setResizable(false);
       /*Color minhaCor = new Color(204,204,204);*/
       Color minhaCor = new Color(240,240,240);
        getContentPane().setBackground(minhaCor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CaractereInserido = new javax.swing.JTextField();
        EscolhaAlgoritmo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ButtonIniciar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        LabelSecundario1 = new javax.swing.JLabel();
        LabelSecundario2 = new javax.swing.JLabel();
        LabelSecundario3 = new javax.swing.JLabel();
        LabelSecundario4 = new javax.swing.JLabel();
        LabelSecundario8 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        LabelSecundario5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        LabelSecundario6 = new javax.swing.JLabel();
        LabelSecundario7 = new javax.swing.JLabel();
        LabelSecundario12 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        LabelSecundario9 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        LabelSecundario10 = new javax.swing.JLabel();
        LabelSecundario11 = new javax.swing.JLabel();
        LabelSecundario16 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        Label15 = new javax.swing.JLabel();
        Label16 = new javax.swing.JLabel();
        LabelSecundario13 = new javax.swing.JLabel();
        Label14 = new javax.swing.JLabel();
        LabelSecundario14 = new javax.swing.JLabel();
        LabelSecundario15 = new javax.swing.JLabel();
        LabelFreq1 = new javax.swing.JLabel();
        LabelFreq2 = new javax.swing.JLabel();
        LabelFreq3 = new javax.swing.JLabel();
        LabelFreq4 = new javax.swing.JLabel();
        LabelFreq5 = new javax.swing.JLabel();
        LabelFreq6 = new javax.swing.JLabel();
        LabelFreq7 = new javax.swing.JLabel();
        LabelFreq8 = new javax.swing.JLabel();
        LabelFreq9 = new javax.swing.JLabel();
        LabelFreq10 = new javax.swing.JLabel();
        LabelFreq11 = new javax.swing.JLabel();
        LabelFreq12 = new javax.swing.JLabel();
        LabelFreq13 = new javax.swing.JLabel();
        LabelFreq14 = new javax.swing.JLabel();
        LabelFreq15 = new javax.swing.JLabel();
        LabelFreq16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Substituição");

        CaractereInserido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CaractereInserido.setText("A");
        CaractereInserido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaractereInseridoActionPerformed(evt);
            }
        });

        EscolhaAlgoritmo.setBackground(new java.awt.Color(102, 102, 102));
        EscolhaAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "S.C", "LFU" }));
        EscolhaAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaAlgoritmoActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Digite o campo:");

        ButtonIniciar.setBackground(new java.awt.Color(0, 102, 153));
        ButtonIniciar.setText("Iniciar");
        ButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 153));
        jButton2.setText("Reiniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Selecione o processo:");

        Label1.setBackground(new java.awt.Color(240, 240, 240));
        Label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("G");

        Label2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label2.setText("B");

        Label3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label3.setText("F");

        Label4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label4.setText("A");

        LabelSecundario1.setBackground(new java.awt.Color(255, 255, 255));
        LabelSecundario1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario1.setText("id: k bitR: 1");

        LabelSecundario2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario2.setText("id: k bitR: 1");

        LabelSecundario3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario3.setText("id: k bitR: 1");

        LabelSecundario4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario4.setText("id: k bitR: 1");

        LabelSecundario8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario8.setText("id: k bitR: 1");

        Label5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label5.setText("R");

        Label7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label7.setText("E");

        Label8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label8.setText("Z");

        LabelSecundario5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario5.setText("id: k bitR: 1");

        Label6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label6.setText("Q");

        LabelSecundario6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario6.setText("id: k bitR: 1");

        LabelSecundario7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario7.setText("id: k bitR: 1");

        LabelSecundario12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario12.setText("id: k bitR: 1");

        Label9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label9.setText("T");

        Label11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label11.setText("K");

        Label12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label12.setText("M");

        LabelSecundario9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario9.setText("id: k bitR: 1");

        Label10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label10.setText("Y");

        LabelSecundario10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario10.setText("id: k bitR: 1");

        LabelSecundario11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario11.setText("id: k bitR: 1");

        LabelSecundario16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario16.setText("id: k bitR: 1");

        Label13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label13.setText("N");

        Label15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label15.setText("Ç");

        Label16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label16.setText("v");

        LabelSecundario13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario13.setText("id: k bitR: 1");

        Label14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label14.setText("X");

        LabelSecundario14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario14.setText("id: k bitR: 1");

        LabelSecundario15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelSecundario15.setText("id: k bitR: 1");

        LabelFreq1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq1.setText("jLabel4");

        LabelFreq2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq2.setText("jLabel5");

        LabelFreq3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq3.setText("jLabel6");

        LabelFreq4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq4.setText("jLabel7");

        LabelFreq5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq5.setText("jLabel8");

        LabelFreq6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq6.setText("jLabel9");

        LabelFreq7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq7.setText("jLabel10");

        LabelFreq8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq8.setText("jLabel11");

        LabelFreq9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq9.setText("jLabel12");

        LabelFreq10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq10.setText("jLabel13");

        LabelFreq11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq11.setText("jLabel14");

        LabelFreq12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq12.setText("jLabel15");

        LabelFreq13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq13.setText("jLabel16");

        LabelFreq14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq14.setText("jLabel17");

        LabelFreq15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq15.setText("jLabel18");

        LabelFreq16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelFreq16.setText("jLabel19");

        jButton1.setText("Sobre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Ajuda");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(CaractereInserido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EscolhaAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Label13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(196, 196, 196)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelFreq13)
                                            .addComponent(LabelSecundario13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelSecundario5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelFreq5)
                                            .addComponent(LabelSecundario1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelFreq1))
                                        .addGap(0, 8, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addComponent(LabelSecundario9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelFreq9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(440, Short.MAX_VALUE)
                                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LabelSecundario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelSecundario14, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addComponent(LabelSecundario10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelSecundario6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Label14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LabelSecundario11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(143, 143, 143))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelSecundario15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelFreq11)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(Label15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(LabelSecundario3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelFreq10)
                                    .addComponent(LabelFreq14))
                                .addGap(56, 56, 56)
                                .addComponent(LabelFreq15))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelFreq2)
                                            .addComponent(LabelFreq6)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(Label10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(Label11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(LabelFreq3)
                                            .addComponent(LabelFreq7)
                                            .addComponent(LabelSecundario7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelSecundario8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(LabelFreq4)
                                            .addComponent(LabelSecundario4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(Label12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(LabelSecundario12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Label16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LabelFreq12))
                                            .addComponent(LabelSecundario16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelFreq16)
                                            .addComponent(LabelFreq8))))))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CaractereInserido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EscolhaAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelSecundario2)
                                    .addComponent(LabelSecundario1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSecundario4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelSecundario3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelFreq2)
                                    .addComponent(LabelFreq3)
                                    .addComponent(LabelFreq4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelFreq1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelSecundario6)
                                    .addComponent(LabelSecundario5)
                                    .addComponent(LabelSecundario7)
                                    .addComponent(LabelSecundario8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LabelFreq6)
                                    .addComponent(LabelFreq5)
                                    .addComponent(LabelFreq7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelFreq8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelSecundario11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelFreq11))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Label12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LabelSecundario12))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Label10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(LabelSecundario10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LabelSecundario9))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LabelFreq12)
                                        .addComponent(LabelFreq10))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Label9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(LabelFreq9)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Label15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelSecundario14)
                                        .addComponent(LabelSecundario15)
                                        .addComponent(LabelSecundario13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelFreq14)
                                        .addComponent(LabelFreq15)
                                        .addComponent(LabelFreq13)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Label16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelSecundario16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LabelFreq16))))
                        .addGap(26, 26, 26))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CaractereInseridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaractereInseridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaractereInseridoActionPerformed

    private void EscolhaAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaAlgoritmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscolhaAlgoritmoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int n = 4;
        
        Processo.geraMatriz(n);
        
        this.mostraMatriz(Processo.getMatriz(), n);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarActionPerformed
        // TODO add your handling code here:
        
        if(EscolhaAlgoritmo.getSelectedItem().equals("FIFO")){
            Algoritmos novoFifo = new Algoritmos();
   
            Processo novoProcesso = new Processo(CaractereInserido.getText().charAt(0), 1, 50);
            
            novoFifo.fifo(Processo.getMatriz(), novoProcesso);
            
            mostraMatriz(Processo.getMatriz(), 4);
            
        }else if(EscolhaAlgoritmo.getSelectedItem().equals("LFU")){
            Algoritmos novoFifo = new Algoritmos();
   
            Processo novoProcesso = new Processo(CaractereInserido.getText().charAt(0), 1, 50);
            
            novoFifo.lfu(Processo.getMatriz(), novoProcesso);
            mostraMatriz(Processo.getMatriz(), 4);
            
        }else if(EscolhaAlgoritmo.getSelectedItem().equals("S.C")){
            Algoritmos novoFifo = new Algoritmos();
   
            Processo novoProcesso = new Processo(CaractereInserido.getText().charAt(0), 1, 50);
            
            novoFifo.segundaChance(Processo.getMatriz(), novoProcesso);
            mostraMatriz(Processo.getMatriz(), 4);
            
        }
        
    }//GEN-LAST:event_ButtonIniciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Sobre().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new Ajuda().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }
    /*
    public Processo[][] geraMatriz(int n){
        Processo tabelaProc[][] = new Processo[n][n];

        Random random = new Random();
        
        for(int i = 0; i < n; i++){
            for(int j = 0; j < n; j++){
                char caractAlea = (char) (random.nextInt(26)+'a');
                
                for(int l = 0; i < n; i++){
                    for(int c = 0; c < n; c++){
                        if(caractAlea == tabelaProc[i][j].getId()){
                            caractAlea = (char) (random.nextInt(26)+'a');
                        }
                    }
                }
                
                int bitAlea = (int) (random.nextInt(2));
                int freq = (int) (random.nextInt(101));
                tabelaProc[i][j] = new Processo(caractAlea, bitAlea, freq);
                //tabelaProc[i][j].setId(caractAlea);
                
            }
        }
        
        return tabelaProc;
    }*/
    
    public void mostraMatriz(Processo tabelaProc[][], int n){
        /*DefaultTableModel model = (DefaultTableModel) tblMatriz.getModel();
        
        model.setRowCount(tabelaProc.length);
        model.setColumnCount(tabelaProc.length);
        
        for(int i = 0; i < n; i++){
            for(int j = 0; j < n; j++){
                tblMatriz.setValueAt(tabelaProc[i][j].toString(), i, j);
               //tblMatriz.setValueAt(tabelaProc[i][j].getBitR(), i, j);
            }
        }
        */
        
        Label1.setText(tabelaProc[0][0].getStringId());
        Label2.setText(tabelaProc[0][1].getStringId());
        Label3.setText(tabelaProc[0][2].getStringId());
        Label4.setText(tabelaProc[0][3].getStringId());
        Label5.setText(tabelaProc[1][0].getStringId());
        Label6.setText(tabelaProc[1][1].getStringId());
        Label7.setText(tabelaProc[1][2].getStringId());
        Label8.setText(tabelaProc[1][3].getStringId());
        Label9.setText(tabelaProc[2][0].getStringId());
        Label10.setText(tabelaProc[2][1].getStringId());
        Label11.setText(tabelaProc[2][2].getStringId());
        Label12.setText(tabelaProc[2][3].getStringId());
        Label13.setText(tabelaProc[3][0].getStringId());
        Label14.setText(tabelaProc[3][1].getStringId());
        Label15.setText(tabelaProc[3][2].getStringId());
        Label16.setText(tabelaProc[3][3].getStringId());
        
        
        LabelSecundario1.setText(tabelaProc[0][0].getStringBitR_EOrdem());
        LabelSecundario2.setText(tabelaProc[0][1].getStringBitR_EOrdem());
        LabelSecundario3.setText(tabelaProc[0][2].getStringBitR_EOrdem());
        LabelSecundario4.setText(tabelaProc[0][3].getStringBitR_EOrdem());
        LabelSecundario5.setText(tabelaProc[1][0].getStringBitR_EOrdem());
        LabelSecundario6.setText(tabelaProc[1][1].getStringBitR_EOrdem());
        LabelSecundario7.setText(tabelaProc[1][2].getStringBitR_EOrdem());
        LabelSecundario8.setText(tabelaProc[1][3].getStringBitR_EOrdem());
        LabelSecundario9.setText(tabelaProc[2][0].getStringBitR_EOrdem());
        LabelSecundario10.setText(tabelaProc[2][1].getStringBitR_EOrdem());
        LabelSecundario11.setText(tabelaProc[2][2].getStringBitR_EOrdem());
        LabelSecundario12.setText(tabelaProc[2][3].getStringBitR_EOrdem());
        LabelSecundario13.setText(tabelaProc[3][0].getStringBitR_EOrdem());
        LabelSecundario14.setText(tabelaProc[3][1].getStringBitR_EOrdem());
        LabelSecundario15.setText(tabelaProc[3][2].getStringBitR_EOrdem());
        LabelSecundario16.setText(tabelaProc[3][3].getStringBitR_EOrdem());
        
        
        LabelFreq1.setText(tabelaProc[0][0].getStringFreq());
        LabelFreq2.setText(tabelaProc[0][1].getStringFreq());
        LabelFreq3.setText(tabelaProc[0][2].getStringFreq());
        LabelFreq4.setText(tabelaProc[0][3].getStringFreq());
        LabelFreq5.setText(tabelaProc[1][0].getStringFreq());
        LabelFreq6.setText(tabelaProc[1][1].getStringFreq());
        LabelFreq7.setText(tabelaProc[1][2].getStringFreq());
        LabelFreq8.setText(tabelaProc[1][3].getStringFreq());
        LabelFreq9.setText(tabelaProc[2][0].getStringFreq());
        LabelFreq10.setText(tabelaProc[2][1].getStringFreq());
        LabelFreq11.setText(tabelaProc[2][2].getStringFreq());
        LabelFreq12.setText(tabelaProc[2][3].getStringFreq());
        LabelFreq13.setText(tabelaProc[3][0].getStringFreq());
        LabelFreq14.setText(tabelaProc[3][1].getStringFreq());
        LabelFreq15.setText(tabelaProc[3][2].getStringFreq());
        LabelFreq16.setText(tabelaProc[3][3].getStringFreq());
        
        
        /*
        jTextArea1.setText(tabelaProc[0][0].toString());
        jTextArea2.setText(tabelaProc[0][1].toString());
        jTextArea3.setText(tabelaProc[0][2].toString());
        jTextArea4.setText(tabelaProc[0][3].toString());
        */
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIniciar;
    private javax.swing.JTextField CaractereInserido;
    private javax.swing.JComboBox<String> EscolhaAlgoritmo;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label15;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JLabel LabelFreq1;
    private javax.swing.JLabel LabelFreq10;
    private javax.swing.JLabel LabelFreq11;
    private javax.swing.JLabel LabelFreq12;
    private javax.swing.JLabel LabelFreq13;
    private javax.swing.JLabel LabelFreq14;
    private javax.swing.JLabel LabelFreq15;
    private javax.swing.JLabel LabelFreq16;
    private javax.swing.JLabel LabelFreq2;
    private javax.swing.JLabel LabelFreq3;
    private javax.swing.JLabel LabelFreq4;
    private javax.swing.JLabel LabelFreq5;
    private javax.swing.JLabel LabelFreq6;
    private javax.swing.JLabel LabelFreq7;
    private javax.swing.JLabel LabelFreq8;
    private javax.swing.JLabel LabelFreq9;
    private javax.swing.JLabel LabelSecundario1;
    private javax.swing.JLabel LabelSecundario10;
    private javax.swing.JLabel LabelSecundario11;
    private javax.swing.JLabel LabelSecundario12;
    private javax.swing.JLabel LabelSecundario13;
    private javax.swing.JLabel LabelSecundario14;
    private javax.swing.JLabel LabelSecundario15;
    private javax.swing.JLabel LabelSecundario16;
    private javax.swing.JLabel LabelSecundario2;
    private javax.swing.JLabel LabelSecundario3;
    private javax.swing.JLabel LabelSecundario4;
    private javax.swing.JLabel LabelSecundario5;
    private javax.swing.JLabel LabelSecundario6;
    private javax.swing.JLabel LabelSecundario7;
    private javax.swing.JLabel LabelSecundario8;
    private javax.swing.JLabel LabelSecundario9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
